# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               CR/LF
tagline:             Max Arturo's Various Thoughts
url:                 http://maxarturoas.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Max Arturo Alcalá Sáinz
  url:               https://twitter.com/maxarturoas
  email:             maxarturo@gmail.com

# Custom vars
version:             1.0.0
github:              https://github.com/maxArturo
